List<String> phases = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
];
List<String> categories = [
  'Admin',
  'Building & Roads',
  'Mechanical',
  'Electrical',
  'Sewerage',
  'Water Supply',
];
final admin = {
  '1': 'Garbage Basket',
  '2': 'Garbage Bags',
  '3': 'Waste Management',
  '4': 'Debris & Wild Growth',
  '5': 'Dengue Spray',
  '6': 'Cleaning of Plots',
};
final building = {
  '1': 'Painting & Sign Writing',
  '2': 'Wood Work / Carpenting',
  '3': 'Welding Works',
  '4': 'Masonary',
  '5': 'Road Repair & Patch Work',
};
final mechanical = {
  '1': 'Gen Sets',
  '2': 'Motor Winding',
  '3': 'SDSs / TWs Motor Winding',
};
final electrical = {
  '1': 'Street Lights',
  '2': 'Parks',
  '3': 'Masajids & Offrs Accn',
  '4': 'Family Qtrs & SM Accn',
  '5': 'ACs',
  '6': 'Tubewells',
  '7': 'Traffic Signals',
  '8': 'Sound Sys',
  '9': 'UPS Sys',
  '10': 'U/G Elect',
};
final sewerage = {
  '1': 'Line Blockage',
  '2': 'Sew Connection',
  '3': 'Main Hole Cover',
  '4': 'Septic Tank Cleaning',
  '5': 'Connection Replacement',
};
final watersupply = {
  '1': 'New / Replacement Connection',
  '2': 'Line Leakage',
  '3': 'Low Pressure',
};

final phase1 = {
  '1': 'Sector A',
  '2': 'Sector B',
  '3': 'Sector C',
  '4': 'Sector D',
  '5': 'Sector E',
  '6': 'Sector F',
  '7': 'Sector G',
  '8': 'Sector H',
  '9': 'Sector J',
  '10': 'Sector K',
  '11': 'Sector L',
  '12': 'Sector M',
  '13': 'Sector N',
  '14': 'Sector P',
};
final phase2 = {
  '1': 'Sector Q',
  '2': 'Sector R',
  '3': 'Sector S',
  '4': 'Sector T',
  '5': 'Sector U',
  '6': 'Sector V',
};
final phase3 = {
  '1': 'Sector W',
  '2': 'Sector X',
  '3': 'Sector Y',
  '4': 'Sector Z',
  '5': 'Sector XX',
};
final phase4 = {
  '1': 'Sector AA',
  '2': 'Sector BB',
  '3': 'Sector CC',
  '4': 'Sector DD',
  '5': 'Sector EE',
  '6': 'Sector FF',
  '7': 'Sector GG',
  '8': 'Sector HH',
  '9': 'Sector JJ',
  '10': 'Sector KK',
};
final phase5 = {
  '1': 'Sector A',
  '2': 'Sector B',
  '3': 'Sector C',
  '4': 'Sector D',
  '5': 'Sector E',
  '6': 'Sector F',
  '7': 'Sector G',
  '8': 'Sector H',
  '9': 'Sector J',
  '10': 'Sector K',
  '11': 'Sector L',
  '12': 'Sector M',
};
final phase6 = {
  '1': 'Sector A',
  '2': 'Sector B',
  '3': 'Sector C',
  '4': 'Sector D',
  '5': 'Sector E',
  '6': 'Sector F',
  '7': 'Sector G',
  '8': 'Sector H',
  '9': 'Sector I',
  '10': 'Sector J',
  '11': 'Sector K',
  '12': 'Sector L',
  '13': 'Sector M',
  '14': 'Sector N',
};
final phase7 = {
  '1': 'Sector P',
  '2': 'Sector Q',
  '3': 'Sector R',
  '4': 'Sector S',
  '5': 'Sector T',
  '6': 'Sector U',
  '7': 'Sector V',
  '8': 'Sector W',
  '9': 'Sector X',
  '10': 'Sector Y',
  '11': 'Sector Z',
};
final phase8 = {
  '1': 'Sector A',
  '2': 'Sector B',
  '3': 'Sector C',
  '4': 'Sector D',
  '5': 'Sector E',
  '6': 'Sector F',
  '7': 'Sector G',
  '8': 'Sector H',
  '9': 'Sector I',
  '10': 'Sector J',
  '11': 'Sector K',
  '12': 'Sector L',
  '13': 'Sector M',
  '14': 'Sector N',
  '15': 'Sector O',
  '16': 'Sector P',
  '17': 'Sector Q',
  '18': 'Sector R',
  '19': 'Sector S',
  '20': 'Sector T',
  '21': 'Sector U',
  '22': 'Sector V',
  '23': 'Sector W',
  '24': 'Sector X',
  '25': 'Sector Y',
  '26': 'Sector Z',
};
final phase9 = {
  '1': 'Sector A',
  '2': 'Sector B',
  '3': 'Sector C',
  '4': 'Sector D',
  '5': 'Sector E',
  '6': 'Sector F',
  '7': 'Sector G',
  '8': 'Sector H',
  '9': 'Sector I',
  '10': 'Sector J',
  '11': 'Sector K',
  '12': 'Sector L',
  '13': 'Sector M',
  '14': 'Sector N',
  '15': 'Sector O',
  '16': 'Sector P',
  '17': 'Sector Q',
  '18': 'Sector R',
  '19': 'Sector S',
  '20': 'Sector T',
  '21': 'Sector U',
  '22': 'Sector V',
  '23': 'Sector W',
  '24': 'Sector X',
  '25': 'Sector Y',
  '26': 'Sector Z',
};
